apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-l1io
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-l1io
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-l1io
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-l1io
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-l1io
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-hpje-tenant/appstudio/dc-metro-map-l1io@sha256:19ee20627210bae8e17c8a9e01e640070d20f399f05c708bc0f0a66799dd6126
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
